# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Yggdrasill"
license = "MIT"
licenselink = "https://github.com/rudeigerc/yggdrasill/blob/master/LICENSE"
description = "A minimal theme."

homepage = "https://github.com/rudeigerc/yggdrasill"

demosite = "https://rudeigerc.dev"

tags = ["minimal", "blog"]
features = ["blog"]

[author]
name = "Yuchen Cheng"
homepage = "https://rudeigerc.dev"
