baseURL = "https://yggdrasill.rudeigerc.dev/"
title = "Theme Yggdrasill"
author = "Steve Francia"
copyright = "Copyright © 2008–2019, Steve Francia and the Hugo Authors; all rights reserved."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

theme = "github.com/rudeigerc/yggdrasill"

[menu]

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/posts"
  weight = 2

[[menu.main]]
  name = "Catagories"
  url = "/categories"
  weight = 3

# [[menu.main]]
#   name = "Series"
#   url = "/series"
#   weight = 4

[[menu.main]]
  name = "Tags"
  url = "/tags"
  weight = 5

[[menu.main]]
  name = "About"
  url = "/about"
  weight = 6

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

[params]
  subtitle = "A minimal theme for Hugo"
  description = "A minimal theme for Hugo"

  [params.giscus]
    dataRepo = "rudeigerc/yggdrasill"
    dataRepoID = "MDEwOlJlcG9zaXRvcnkyODQyNzI2NTE="
    dataCategory = "Comments"
    dataCategoryID = "DIC_kwDOEPGoC84CQFk4"

# custom social icons
# Reference: https://fontawesome.com/icons
[[params.social]]
  name = "GitHub"
  url = "https://github.com/rudeigerc/yggdrasill"
  type = "brands"
  icon = "github"

[module]
[[module.imports]]
  path = "github.com/rudeigerc/yggdrasill"
